
const menuData = [
    {
        name: "Sweet Item",
        image: "/img/cake-9.jpg",
        price: 30,
        category: ["Sweets", "All"],
    },
    {
        name: "Cupcake Item",
        image: "/img/cupcake-10.jpg",
        price: 24,
        category: ["Cupcakes", "All"],
    },
    {
        name: "Cake Item",
        image: "img/cake-11.jpg",
        price: 26,
        category: ["Cakes", "All"],
    },
    {
        name: "Doughnut Item",
        image: "/img/doughnut-11.jpg",
        price: 82,
        category: ["Doughnuts", "All"],
    },
    {
        name: "Sweets Item",
        image: "/img/cupcake-14.jpg",
        price: 45,
        category: ["Sweets", "All"],
    },
    {
        name: "Cupcake Item",
        image: "/img/cupcake-15.jpg",
        price: 80,
        category: ["Cupcakes", "All"],
    },
    {
        name: "Cake Item",
        image: "/img/cake-8.jpg",
        price: 250,
        category: ["Cakes", "All"],
    },
    {
        name: "Doughnut Item",
        image: "/img/doughnut-9.jpg",
        price: 15,
        category: ["Doughnuts", "All"],
    },
    {
        name: "Sweets Item",
        image: "/img/sweets-4.jpg",
        price: 48,
        category: ["Sweets", "All"],
    },
    {
        name: "Sweets Item",
        image: "/img/sweets-1.jpeg",
        price: 48,
        category: ["Sweets", "All"],
    },
    {
        name: "Sweets Item",
        image: "/img/sweets-2.jpeg",
        price: 48,
        category: ["Sweets", "All"],
    },
    {
        name: "Sweets Item",
        image: "/img/sweets-3.jpeg",
        price: 48,
        category: ["Sweets", "All"],
    },
    {
        name: "Sweets Item",
        image: "/img/portrait-2.jpg",
        price: 48,
        category: ["Sweets", "All"],
    },
    {
        name: "Sweets Item",
        image: "/img/cookie.jpg",
        price: 48,
        category: ["Sweets", "All"],
    },
    {
        name: "Cupcake Item",
        image: "/img/cupcake-12.jpg",
        price: 27,
        category: ["Cupcakes", "All"],
    },
    {
        name: "Cake Item",
        image: "/img/sweets-5.jpg",
        price: 500,
        category: ["Cakes", "All"],
    },
    {
        name: "Cake Item",
        image: "/img/cake-13.jpg",
        price: 450,
        category: ["Cakes", "All"],
    },
    {
        name: "Cake Item",
        image: "/img/cake-14.jpg",
        price: 150,
        category: ["Cakes", "All"],
    },
    {
        name: "Cake Item",
        image: "/img/cake-15.jpg",
        price: 280,
        category: ["Cakes", "All"],
    },
    {
        name: "Cake Item",
        image: "/img/cake-16.jpg",
        price: 350,
        category: ["Cakes", "All"],
    },
    {
        name: "Cake Item",
        image: "/img/cake-17.jpg",
        price: 520,
        category: ["Cakes", "All"],
    },
    {
        name: "Cake Item",
        image: "/img/cake-18.jpg",
        price: 150,
        category: ["Cakes", "All"],
    },
    {
        name: "Cake Item",
        image: "/img/cake-19.jpg",
        price: 260,
        category: ["Cakes", "All"],
    },
    {
        name: "Cupcake Item",
        image: "/img/cupcake-7.jpg",
        price: 24,
        category: ["Cupcakes", "All"],
    },
    {
        name: "Cupcake Item",
        image: "/img/cupcake-8.jpg",
        price: 24,
        category: ["Cupcakes", "All"],
    },
    {
        name: "Cupcake Item",
        image: "/img/cupcake-9.jpg",
        price: 24,
        category: ["Cupcakes", "All"],
    },
    {
        name: "Cupcake Item",
        image: "/img/cupcake-13.jpg",
        price: 24,
        category: ["Cupcakes", "All"],
    },
    {
        name: "Cupcake Item",
        image: "/img/cupcake-16.jpg",
        price: 24,
        category: ["Cupcakes", "All"],
    },
    {
        name: "Cupcake Item",
        image: "/img/cupcake-17.jpg",
        price: 24,
        category: ["Cupcakes", "All"],
    },
    {
        name: "Cupcake Item",
        image: "/img/cupcake-11.jpg",
        price: 24,
        category: ["Cupcakes", "All"],
    },
    {
        name: "Doughnut Item",
        image: "/img/doughnut-4.jpg",
        price: 15,
        category: ["Doughnuts", "All"],
    },
    {
        name: "Doughnut Item",
        image: "/img/doughnut-6.jpg",
        price: 15,
        category: ["Doughnuts", "All"],
    },
    {
        name: "Doughnut Item",
        image: "/img/doughnut-7.jpg",
        price: 15,
        category: ["Doughnuts", "All"],
    },
    {
        name: "Doughnut Item",
        image: "/img/doughnut-8.jpg",
        price: 15,
        category: ["Doughnuts", "All"],
    },
    {
        name: "Doughnut Item",
        image: "/img/doughnut-11.jpg",
        price: 15,
        category: ["Doughnuts", "All"],
    },
    {
        name: "Doughnut Item",
        image: "/img/doughnut-16.jpg",
        price: 15,
        category: ["Doughnuts", "All"],
    },
    {
        name: "Doughnut Item",
        image: "/img/doughnut-17.jpg",
        price: 15,
        category: ["Doughnuts", "All"],
    },
    {
        name: "Doughnut Item",
        image: "/img/doughnut-18.jpg",
        price: 15,
        category: ["Doughnuts", "All"],
    },
    {
        name: "Doughnut Item",
        image: "/img/doughnut-header-4.jpg",
        price: 15,
        category: ["Doughnuts", "All"],
    },
]

export default menuData;